services:
  antivirus-gui:
    image: ghcr.io/winretro/clam-scheduler:latest
    container_name: antivirus-gui
    ports:
      - "${HOST_UI_PORT:-8089}:8089"
    environment:
      - SCAN_DIR=/data
      - TZ=${TZ:-UTC}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./data:/app/data
      # This is dynamic. It resolves whatever path is in your .env file
      - ${HOST_SCAN_TARGET}:/data:ro
    depends_on:
      - clamav
    restart: unless-stopped

  clamav:
    image: clamav/clamav:latest
    container_name: clamav_engine
    group_add:
      - "${PGID}"
    ports:
      - "3310:3310"
    # This also uses the exact same dynamic variable
    volumes:
      - ${HOST_SCAN_TARGET}:/data:ro
    restart: unless-stopped
