services:
  clam-scheduler-gui:
    image: ghcr.io/winretro/clam-scheduler:latest
    container_name: clam-scheduler-gui
    ports:
      # Expose ClamAV GUI on host's port 8089
      - 8089:8089
    environment:
      - SCAN_DIR=/data
      # Set the timezone to have cron reflect local time
      - TZ=Etc/UTC
      # Set the log level to INFO vs DEBUG
      - LOG_LEVEL=INFO
      # Set the permissions to give the container ro access to host path
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/app/data
      # Replace with the absolute host path to be scanned
      - /path/to/your/nas/data:/data:ro
    depends_on:
      - clamav
    restart: unless-stopped

  clamav:
    image: clamav/clamav:latest
    container_name: clamav_engine
    group_add:
      # Must match the PGID above
      - 1000
    ports:
      - 3310:3310
    volumes:
      # Must match the exact path mapped in clam-scheduler-gui above
      - /path/to/your/nas/data:/data:ro
    restart: unless-stopped
